### ISSUE TITLE
target tracking subsystem

### ISSUE THREAD

**Issue by KiraA-R** [Team997Coders/pyswerve_2024#11]
code needs to be refactored from twin-stick drive

**Comment by jamesra** [comment]
We want a way to lock the robot's heading to a target field position (X,Y) or an angle (theta).  I'd expose two methods, one sets an angle.  One sets a field location.  After thinking more this is probably a command and not a subsystem.  It runs continuously once a user presses a button and then is disabled when the user presses another button to choose a new target or return to a manual control.  This is an intermediate project that may get more advanced as it is integrated into the robot.  Twin-Stick jitter problem needs to be solved before it is useful.

**Comment by jamesra** [comment]
Worked with Eric to refactor.  Checked in[ initial code](https://github.com/Team997Coders/pyswerve_2024/commit/09e8c9c8c5071b37e07ae9b3e2b2ecfbb9c58419) so other commands can be written to use it.  Needs testing before closing.
