### ISSUE TITLE
Brown out problem

### ISSUE THREAD

**Issue by Yuxuan1103** [Team997Coders/pyswerve_2024#69]
Our current problem is that the 15 CAN SparkMax takes too much power and cause a brown out. Can be that some electrical issue. There is a place in the code that takes extra powers, I think. Likely to be on the intake and swerve.

**Comment by Yuxuan1103** [comment]
We fixed it I think

**Comment by Philipp-BH** [comment]
Yep, this appears to be no longer be an issue after the climber code was changed
